/* Generated by xml2scd.pl */


/* Unions */

typedef struct {
	uint16	unknown[3];
} aot_params_dummy_t;

typedef struct {
	int16	x;
	int16	y;
	int16	z;
} aot_params_door_t;

typedef struct {
	uint16	type;
	uint16	amount;
	uint16	unknown;
} aot_params_item_t;

typedef struct {
	uint16	unknown[3];
} aot_params_standard_t;

typedef struct {
	uint8	id;
	uint8	unknown0;
	uint16	unknown1[2];
} aot_params_message_t;

typedef struct {
	uint8	cond;
	uint8	unknown0;
	uint8	ex_opcode;
	uint8	event;
	uint16	unknown1;
} aot_params_event_t;

typedef struct {
	uint16	unknown[3];
} aot_params_flag_change_t;

typedef struct {
	uint16	unknown[3];
} aot_params_water_t;

typedef struct {
	uint16	unknown[3];
} aot_params_move_t;

typedef struct {
	uint16	unknown[3];
} aot_params_typewriter_t;

typedef struct {
	uint16	unknown[3];
} aot_params_itembox_t;

typedef struct {
	uint16	unknown[3];
} aot_params_damage_t;

typedef struct {
	uint16	unknown[3];
} aot_params_status_t;

typedef struct {
	uint16	unknown[3];
} aot_params_drawer_t;

typedef struct {
	uint16	unknown[3];
} aot_params_windows_t;

typedef union {
	aot_params_dummy_t	dummy;
	aot_params_door_t	door;
	aot_params_item_t	item;
	aot_params_standard_t	standard;
	aot_params_message_t	message;
	aot_params_event_t	event;
	aot_params_flag_change_t	flag_change;
	aot_params_water_t	water;
	aot_params_move_t	move;
	aot_params_typewriter_t	typewriter;
	aot_params_itembox_t	itembox;
	aot_params_damage_t	damage;
	aot_params_status_t	status;
	aot_params_drawer_t	drawer;
	aot_params_windows_t	windows;
} aot_params_u;

typedef struct {
	uint8	opcode;
} script_inst_nop_t;

typedef struct {
	uint8	opcode;
	uint8	ret_value;
} script_inst_evt_end_t;

typedef struct {
	uint8	opcode;
} script_inst_evt_next_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_evt_chain_t;

typedef struct {
	uint8	opcode;
	uint8	cond;
	uint8	ex_opcode;
	uint8	event;
} script_inst_evt_exec_t;

typedef struct {
	uint8	opcode;
	uint8	event;
} script_inst_evt_kill_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_if_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_else_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_endif_t;

typedef struct {
	uint8	opcode;
} script_inst_sleep_t;

typedef struct {
	uint8	opcode;
	uint8	delay;
	uint8	unknown;
} script_inst_sleeping_t;

typedef struct {
	uint8	opcode;
} script_inst_wsleep_t;

typedef struct {
	uint8	opcode;
} script_inst_wsleeping_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
	uint16	count;
} script_inst_for_t;

typedef struct {
} script_inst_0e_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_next_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_while_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_ewhile_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_do_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_edwhile_t;

typedef struct {
	uint8	opcode;
	uint8	varw;
	uint16	block_length;
} script_inst_switch_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
	uint16	value;
} script_inst_case_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_default_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_eswitch_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	unknown1;
	uint8	unknown2;
	int16	rel_offset;
} script_inst_goto_t;

typedef struct {
	uint8	opcode;
	uint8	event;
} script_inst_gosub_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_return_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_break_t;

typedef struct {
	uint8	opcode;
} script_inst_break_point_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_eval_cc_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_set1e_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_set1f_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	operation;
	uint8	varw;
	uint16	value;
} script_inst_calc_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_21_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
	uint8	ex_opcode;
	uint8	event;
} script_inst_evt_cut_t;

typedef struct {
	uint8	opcode;
} script_inst_23_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_chaser_evt_clr_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_map_open_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_point_add_t;

typedef struct {
	uint8	opcode;
} script_inst_door_ck_t;

typedef struct {
	uint8	opcode;
} script_inst_diedemo_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[7];
} script_inst_dir_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_parts_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_vloop_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_ota_be_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_line_start_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_line_main_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_line_end_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_light_pos_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_light_kido_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	unknown;
	uint8	r;
	uint8	g;
	uint8	b;
} script_inst_light_color_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_ahead_room_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[9];
} script_inst_espr_ctr_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_bgm_tbl_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_item_get_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_om_rev_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_chaser_life_init_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[7];
} script_inst_parts_bomb_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[7];
} script_inst_parts_down_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_chaser_item_set_t;

typedef struct {
	uint8	opcode;
} script_inst_weapon_chg_old_t;

typedef struct {
	uint8	opcode;
	uint8	question;
} script_inst_sel_evt_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_item_lost_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_flr_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	int16	value;
} script_inst_memb_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_memb_set2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_memb_cpy_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	compare;
	uint8	varw;
	uint16	value;
} script_inst_memb_cmp_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	operation;
	uint8	varw;
	uint16	value;
} script_inst_memb_calc_t;

typedef struct {
	uint8	opcode;
	uint8	operation;
	uint8	varw;
	uint8	src;
} script_inst_memb_calc2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[10];
} script_inst_fade_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
	uint8	object;
} script_inst_work_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
	int8	value;
} script_inst_spd_set_t;

typedef struct {
	uint8	opcode;
} script_inst_add_spd_t;

typedef struct {
	uint8	opcode;
} script_inst_add_aspd_t;

typedef struct {
	uint8	opcode;
} script_inst_add_vspd_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_cmp_t;

typedef struct {
	uint8	opcode;
} script_inst_rnd_t;

typedef struct {
	uint8	opcode;
	uint8	camera;
} script_inst_cut_chg_t;

typedef struct {
	uint8	opcode;
} script_inst_cut_old_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_cut_auto_t;

typedef struct {
	uint8	opcode;
	uint8	camera0;
	uint8	camera1;
} script_inst_cut_replace_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_cut_be_set_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	int16	x;
	int16	y;
	int16	z;
} script_inst_pos_set_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	int16	cdir_x;
	int16	cdir_y;
	int16	cdir_z;
} script_inst_dir_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_set_vib0_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_set_vib1_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[7];
} script_inst_set_vib_fade_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_rbj_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown[2];
} script_inst_message_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_rain_set_t;

typedef struct {
	uint8	opcode;
} script_inst_message_off_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_shake_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_weapon_chg_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[10];
} script_inst_60_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown0[2];
	int16	x;
	int16	z;
	int16	w;
	int16	h;
	int16	next_x;
	int16	next_y;
	int16	next_z;
	int16	next_dir;
	uint8	next_stage;
	uint8	next_room;
	uint8	next_camera;
	uint8	unknown2;
	uint8	door_type;
	uint8	door_lock;
	uint8	unknown3;
	uint8	door_locked;
	uint8	door_key;
	uint8	unknown4;
} script_inst_door_aot_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown0[2];
	int16	x0;
	int16	z0;
	int16	x1;
	int16	z1;
	int16	x2;
	int16	z2;
	int16	x3;
	int16	z3;
	int16	next_x;
	int16	next_y;
	int16	next_z;
	int16	next_dir;
	uint8	next_stage;
	uint8	next_room;
	uint8	next_camera;
	uint8	unknown1;
	uint16	unknown2[3];
} script_inst_door_aot_set_4p_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown0[2];
	int16	x;
	int16	z;
	int16	w;
	int16	h;
	uint16	unknown1[3];
} script_inst_aot_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown0[2];
	int16	x0;
	int16	z0;
	int16	x1;
	int16	z1;
	int16	x2;
	int16	z2;
	int16	x3;
	int16	z3;
	uint16	unknown1[3];
} script_inst_aot_set_4p_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	type;
	uint8	trigger;
	aot_params_u	aot_params;
} script_inst_aot_reset_t;

typedef struct {
	uint8	opcode;
	uint8	id;
} script_inst_aot_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[2];
	int16	x;
	int16	z;
	int16	w;
	int16	h;
	uint16	unknown2[4];
} script_inst_item_aot_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[14];
} script_inst_item_aot_set_4p_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[6];
} script_inst_kage_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[7];
} script_inst_super_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_keep_item_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_key_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_trg_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_sca_id_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_om_bomb_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[3];
	int16	x;
	int16	y;
	int16	z;
	uint16	unknown2;
} script_inst_espr_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[8];
} script_inst_espr_on2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[3];
	int16	x;
	int16	y;
	int16	z;
	uint16	unknown2[4];
} script_inst_espr3d_on_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	id;
	uint8	unknown0;
	uint16	unknown1[3];
	int16	x;
	int16	y;
	int16	z;
	uint16	unknown2[4];
} script_inst_espr3d_on2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[4];
} script_inst_espr_kill_t;

typedef struct {
	uint8	opcode;
	uint8	id;
} script_inst_espr_kill2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[2];
} script_inst_espr_kill_all_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[5];
} script_inst_se_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_bgm_ctl_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_xa_on_t;

typedef struct {
	uint8	opcode;
	uint8	id;
} script_inst_movie_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[5];
} script_inst_bgm_tbl_set_t;

typedef struct {
	uint8	opcode;
} script_inst_status_on_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	id;
	uint8	model;
	uint32	unknown1[2];
	int16	x;
	int16	y;
	int16	z;
	int16	dir;
	uint16	unknown2[2];
} script_inst_em_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_mizu_div_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2[3];
	int16	x;
	int16	y;
	int16	z;
	uint16	unknown3;
	uint32	unknown4[4];
} script_inst_om_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_plc_motion_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	int16	x;
	int16	y;
	int16	z;
} script_inst_plc_dest_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[9];
} script_inst_plc_neck_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_ret_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_plc_flg_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_plc_gun_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_gun_eff_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_stop_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_plc_rot_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_plc_cnt_t;

typedef struct {
	uint8	opcode;
} script_inst_splc_ret_t;

typedef struct {
	uint8	opcode;
} script_inst_splc_sce_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_sce_t;

typedef struct {
	uint8	opcode;
} script_inst_spl_weapon_chg_t;

typedef struct {
	uint8	opcode;
	uint8	unknown[3];
} script_inst_plc_mot_num_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_em_reset_t;

typedef union script_inst_u script_inst_t;

union script_inst_u {
	uint8	opcode;
	script_inst_nop_t	i_nop;
	script_inst_evt_end_t	i_evt_end;
	script_inst_evt_next_t	i_evt_next;
	script_inst_evt_chain_t	i_evt_chain;
	script_inst_evt_exec_t	i_evt_exec;
	script_inst_evt_kill_t	i_evt_kill;
	script_inst_if_t	i_if;
	script_inst_else_t	i_else;
	script_inst_endif_t	i_endif;
	script_inst_sleep_t	i_sleep;
	script_inst_sleeping_t	i_sleeping;
	script_inst_wsleep_t	i_wsleep;
	script_inst_wsleeping_t	i_wsleeping;
	script_inst_for_t	i_for;
	script_inst_0e_t	i_0e;
	script_inst_next_t	i_next;
	script_inst_while_t	i_while;
	script_inst_ewhile_t	i_ewhile;
	script_inst_do_t	i_do;
	script_inst_edwhile_t	i_edwhile;
	script_inst_switch_t	i_switch;
	script_inst_case_t	i_case;
	script_inst_default_t	i_default;
	script_inst_eswitch_t	i_eswitch;
	script_inst_goto_t	i_goto;
	script_inst_gosub_t	i_gosub;
	script_inst_return_t	i_return;
	script_inst_break_t	i_break;
	script_inst_break_point_t	i_break_point;
	script_inst_eval_cc_t	i_eval_cc;
	script_inst_set1e_t	i_set1e;
	script_inst_set1f_t	i_set1f;
	script_inst_calc_t	i_calc;
	script_inst_21_t	i_21;
	script_inst_evt_cut_t	i_evt_cut;
	script_inst_23_t	i_23;
	script_inst_chaser_evt_clr_t	i_chaser_evt_clr;
	script_inst_map_open_t	i_map_open;
	script_inst_point_add_t	i_point_add;
	script_inst_door_ck_t	i_door_ck;
	script_inst_diedemo_on_t	i_diedemo_on;
	script_inst_dir_ck_t	i_dir_ck;
	script_inst_parts_set_t	i_parts_set;
	script_inst_vloop_set_t	i_vloop_set;
	script_inst_ota_be_set_t	i_ota_be_set;
	script_inst_line_start_t	i_line_start;
	script_inst_line_main_t	i_line_main;
	script_inst_line_end_t	i_line_end;
	script_inst_light_pos_set_t	i_light_pos_set;
	script_inst_light_kido_set_t	i_light_kido_set;
	script_inst_light_color_set_t	i_light_color_set;
	script_inst_ahead_room_set_t	i_ahead_room_set;
	script_inst_espr_ctr_t	i_espr_ctr;
	script_inst_bgm_tbl_ck_t	i_bgm_tbl_ck;
	script_inst_item_get_ck_t	i_item_get_ck;
	script_inst_om_rev_t	i_om_rev;
	script_inst_chaser_life_init_t	i_chaser_life_init;
	script_inst_parts_bomb_t	i_parts_bomb;
	script_inst_parts_down_t	i_parts_down;
	script_inst_chaser_item_set_t	i_chaser_item_set;
	script_inst_weapon_chg_old_t	i_weapon_chg_old;
	script_inst_sel_evt_on_t	i_sel_evt_on;
	script_inst_item_lost_t	i_item_lost;
	script_inst_flr_set_t	i_flr_set;
	script_inst_memb_set_t	i_memb_set;
	script_inst_memb_set2_t	i_memb_set2;
	script_inst_memb_cpy_t	i_memb_cpy;
	script_inst_memb_cmp_t	i_memb_cmp;
	script_inst_memb_calc_t	i_memb_calc;
	script_inst_memb_calc2_t	i_memb_calc2;
	script_inst_fade_set_t	i_fade_set;
	script_inst_work_set_t	i_work_set;
	script_inst_spd_set_t	i_spd_set;
	script_inst_add_spd_t	i_add_spd;
	script_inst_add_aspd_t	i_add_aspd;
	script_inst_add_vspd_t	i_add_vspd;
	script_inst_ck_t	i_ck;
	script_inst_set_t	i_set;
	script_inst_cmp_t	i_cmp;
	script_inst_rnd_t	i_rnd;
	script_inst_cut_chg_t	i_cut_chg;
	script_inst_cut_old_t	i_cut_old;
	script_inst_cut_auto_t	i_cut_auto;
	script_inst_cut_replace_t	i_cut_replace;
	script_inst_cut_be_set_t	i_cut_be_set;
	script_inst_pos_set_t	i_pos_set;
	script_inst_dir_set_t	i_dir_set;
	script_inst_set_vib0_t	i_set_vib0;
	script_inst_set_vib1_t	i_set_vib1;
	script_inst_set_vib_fade_t	i_set_vib_fade;
	script_inst_rbj_set_t	i_rbj_set;
	script_inst_message_on_t	i_message_on;
	script_inst_rain_set_t	i_rain_set;
	script_inst_message_off_t	i_message_off;
	script_inst_shake_on_t	i_shake_on;
	script_inst_weapon_chg_t	i_weapon_chg;
	script_inst_60_t	i_60;
	script_inst_door_aot_set_t	i_door_aot_set;
	script_inst_door_aot_set_4p_t	i_door_aot_set_4p;
	script_inst_aot_set_t	i_aot_set;
	script_inst_aot_set_4p_t	i_aot_set_4p;
	script_inst_aot_reset_t	i_aot_reset;
	script_inst_aot_on_t	i_aot_on;
	script_inst_item_aot_set_t	i_item_aot_set;
	script_inst_item_aot_set_4p_t	i_item_aot_set_4p;
	script_inst_kage_set_t	i_kage_set;
	script_inst_super_set_t	i_super_set;
	script_inst_keep_item_ck_t	i_keep_item_ck;
	script_inst_key_ck_t	i_key_ck;
	script_inst_trg_ck_t	i_trg_ck;
	script_inst_sca_id_set_t	i_sca_id_set;
	script_inst_om_bomb_t	i_om_bomb;
	script_inst_espr_on_t	i_espr_on;
	script_inst_espr_on2_t	i_espr_on2;
	script_inst_espr3d_on_t	i_espr3d_on;
	script_inst_espr3d_on2_t	i_espr3d_on2;
	script_inst_espr_kill_t	i_espr_kill;
	script_inst_espr_kill2_t	i_espr_kill2;
	script_inst_espr_kill_all_t	i_espr_kill_all;
	script_inst_se_on_t	i_se_on;
	script_inst_bgm_ctl_t	i_bgm_ctl;
	script_inst_xa_on_t	i_xa_on;
	script_inst_movie_on_t	i_movie_on;
	script_inst_bgm_tbl_set_t	i_bgm_tbl_set;
	script_inst_status_on_t	i_status_on;
	script_inst_em_set_t	i_em_set;
	script_inst_mizu_div_t	i_mizu_div;
	script_inst_om_set_t	i_om_set;
	script_inst_plc_motion_t	i_plc_motion;
	script_inst_plc_dest_t	i_plc_dest;
	script_inst_plc_neck_t	i_plc_neck;
	script_inst_plc_ret_t	i_plc_ret;
	script_inst_plc_flg_t	i_plc_flg;
	script_inst_plc_gun_t	i_plc_gun;
	script_inst_plc_gun_eff_t	i_plc_gun_eff;
	script_inst_plc_stop_t	i_plc_stop;
	script_inst_plc_rot_t	i_plc_rot;
	script_inst_plc_cnt_t	i_plc_cnt;
	script_inst_splc_ret_t	i_splc_ret;
	script_inst_splc_sce_t	i_splc_sce;
	script_inst_plc_sce_t	i_plc_sce;
	script_inst_spl_weapon_chg_t	i_spl_weapon_chg;
	script_inst_plc_mot_num_t	i_plc_mot_num;
	script_inst_em_reset_t	i_em_reset;
};
