/* Generated by xml2scd.pl */


/* Unions */

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_nop_t;

typedef struct {
	uint8	opcode;
	uint8	block_length;
} script_inst_if_t;

typedef struct {
	uint8	opcode;
	uint8	block_length;
} script_inst_else_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_endif_t;

typedef struct {
	uint8	opcode;
	uint8	flag;
	uint8	object;
	uint8	value;
} script_inst_bit_test_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_bit_op_t;

typedef struct {
	uint8	opcode;
	uint8	object;
	uint8	compare;
	uint8	value;
} script_inst_stageroomcam_cmp_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	varw;
	uint8	compare;
	uint16	value;
} script_inst_cmp07_t;

typedef struct {
	uint8	opcode;
	uint8	object;
	uint16	value;
} script_inst_stageroomcam_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_cut_set09_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_cut_set0a_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown;
} script_inst_message_on_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	x;
	uint16	y;
	uint16	w;
	uint16	h;
	uint8	unknown0;
	uint8	unknown1;
	uint8	anim;
	uint8	unknown2;
	uint8	unknown3;
	uint8	next_stage_and_room;
	uint16	next_x;
	uint16	next_y;
	uint16	next_z;
	uint16	next_dir;
	uint8	unknown4;
	uint8	unknown5;
} script_inst_door_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	x;
	uint16	y;
	uint16	w;
	uint16	h;
	uint8	type;
	uint8	unknown0;
	uint8	unknown1;
	uint8	unknown2;
	uint8	unknown3;
	uint8	unknown4;
	uint8	unknown5;
	uint8	unknown6;
} script_inst_item_set_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_nop0e_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
} script_inst_0f_t;

typedef struct {
	uint8	opcode;
	uint8	value;
} script_inst_cmp10_eq_t;

typedef struct {
	uint8	opcode;
	uint8	value;
} script_inst_cmp11_eq_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	unknown0;
	uint8	unknown1;
	uint16	unknown2;
	uint16	unknown3;
	uint16	unknown4;
} script_inst_item_attr_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	unknown0;
	uint8	unknown1;
} script_inst_item_attr2_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_14_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_15_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_16_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	type;
	uint16	unknown3;
	uint16	unknown4;
} script_inst_17_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	unknown0;
	uint16	unknown1;
	uint16	unknown2;
	uint16	unknown3;
	uint16	unknown4;
	uint16	unknown5;
	uint16	unknown6;
	uint16	unknown7;
	uint16	unknown8;
	uint16	unknown9;
	uint16	unknown10;
	uint16	unknown11;
} script_inst_item_model_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_19_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_1a_t;

typedef struct {
	uint8	opcode;
	uint8	model;
	uint8	unknown0;
	uint8	killed;
	uint16	unknown1;
	uint16	a;
	uint16	unknown2;
	uint16	x;
	uint16	y;
	uint16	z;
	uint16	unknown3;
	uint8	id;
	uint8	unknown4;
} script_inst_em_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_1c_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_1d_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_1e_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	x;
	uint16	y;
	uint16	z;
	uint16	cdir_x;
	uint16	cdir_y;
	uint16	cdir_z;
	uint16	unknown6;
	uint16	unknown7;
	uint16	unknown8;
	uint16	unknown9;
	uint16	unknown10;
	uint16	unknown11;
	uint16	unknown12;
} script_inst_om_set_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	cdir_x;
	uint16	cdir_y;
	uint16	cdir_z;
	uint16	x;
	uint16	y;
	uint16	z;
} script_inst_plc_pos_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	cdir_x;
	uint16	cdir_y;
	uint16	cdir_z;
	uint16	x;
	uint16	y;
	uint16	z;
} script_inst_em_pos_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_22_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_23_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_24_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_25_t;

typedef struct {
	uint8	opcode;
} script_inst_26_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_27_t;

typedef struct {
	uint8	opcode;
} script_inst_28_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_29_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
} script_inst_2a_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_2b_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_2c_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_2d_t;

typedef struct {
	uint8	opcode;
} script_inst_2e_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_2f_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
} script_inst_30_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_31_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_32_t;

typedef struct {
	uint8	opcode;
	uint8	type;
	uint8	unknown0;
	uint8	unknown1;
} script_inst_33_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
} script_inst_34_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_35_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_36_t;

typedef struct {
	uint8	opcode;
	uint8	row;
	uint8	col;
	uint8	value;
} script_inst_37_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_38_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_39_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_3a_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_3b_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_3c_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
} script_inst_3d_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_3e_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_3f_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
} script_inst_40_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_41_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_42_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_43_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_44_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_45_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
	uint32	unknown5;
	uint32	unknown6;
	uint32	unknown7;
	uint32	unknown8;
	uint32	unknown9;
	uint16	unknown10;
} script_inst_46_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[3];
	uint16	unknown2[3];
} script_inst_47_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_48_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_49_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_4a_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_4b_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_4c_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_4d_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_4e_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_4f_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_50_t;

typedef union script_inst_u script_inst_t;

union script_inst_u {
	uint8	opcode;
	script_inst_nop_t	i_nop;
	script_inst_if_t	i_if;
	script_inst_else_t	i_else;
	script_inst_endif_t	i_endif;
	script_inst_bit_test_t	i_bit_test;
	script_inst_bit_op_t	i_bit_op;
	script_inst_stageroomcam_cmp_t	i_stageroomcam_cmp;
	script_inst_cmp07_t	i_cmp07;
	script_inst_stageroomcam_set_t	i_stageroomcam_set;
	script_inst_cut_set09_t	i_cut_set09;
	script_inst_cut_set0a_t	i_cut_set0a;
	script_inst_message_on_t	i_message_on;
	script_inst_door_set_t	i_door_set;
	script_inst_item_set_t	i_item_set;
	script_inst_nop0e_t	i_nop0e;
	script_inst_0f_t	i_0f;
	script_inst_cmp10_eq_t	i_cmp10_eq;
	script_inst_cmp11_eq_t	i_cmp11_eq;
	script_inst_item_attr_set_t	i_item_attr_set;
	script_inst_item_attr2_set_t	i_item_attr2_set;
	script_inst_14_t	i_14;
	script_inst_15_t	i_15;
	script_inst_16_t	i_16;
	script_inst_17_t	i_17;
	script_inst_item_model_set_t	i_item_model_set;
	script_inst_19_t	i_19;
	script_inst_1a_t	i_1a;
	script_inst_em_set_t	i_em_set;
	script_inst_1c_t	i_1c;
	script_inst_1d_t	i_1d;
	script_inst_1e_t	i_1e;
	script_inst_om_set_t	i_om_set;
	script_inst_plc_pos_set_t	i_plc_pos_set;
	script_inst_em_pos_set_t	i_em_pos_set;
	script_inst_22_t	i_22;
	script_inst_23_t	i_23;
	script_inst_24_t	i_24;
	script_inst_25_t	i_25;
	script_inst_26_t	i_26;
	script_inst_27_t	i_27;
	script_inst_28_t	i_28;
	script_inst_29_t	i_29;
	script_inst_2a_t	i_2a;
	script_inst_2b_t	i_2b;
	script_inst_2c_t	i_2c;
	script_inst_2d_t	i_2d;
	script_inst_2e_t	i_2e;
	script_inst_2f_t	i_2f;
	script_inst_30_t	i_30;
	script_inst_31_t	i_31;
	script_inst_32_t	i_32;
	script_inst_33_t	i_33;
	script_inst_34_t	i_34;
	script_inst_35_t	i_35;
	script_inst_36_t	i_36;
	script_inst_37_t	i_37;
	script_inst_38_t	i_38;
	script_inst_39_t	i_39;
	script_inst_3a_t	i_3a;
	script_inst_3b_t	i_3b;
	script_inst_3c_t	i_3c;
	script_inst_3d_t	i_3d;
	script_inst_3e_t	i_3e;
	script_inst_3f_t	i_3f;
	script_inst_40_t	i_40;
	script_inst_41_t	i_41;
	script_inst_42_t	i_42;
	script_inst_43_t	i_43;
	script_inst_44_t	i_44;
	script_inst_45_t	i_45;
	script_inst_46_t	i_46;
	script_inst_47_t	i_47;
	script_inst_48_t	i_48;
	script_inst_49_t	i_49;
	script_inst_4a_t	i_4a;
	script_inst_4b_t	i_4b;
	script_inst_4c_t	i_4c;
	script_inst_4d_t	i_4d;
	script_inst_4e_t	i_4e;
	script_inst_4f_t	i_4f;
	script_inst_50_t	i_50;
};
