/* Generated by xml2scd.pl */


/* Unions */

typedef struct {
	uint16	unknown[3];
} aot_params_dummy_t;

typedef struct {
	int16	x;
	int16	y;
	int16	z;
} aot_params_door_t;

typedef struct {
	uint16	type;
	uint16	amount;
	uint16	unknown;
} aot_params_item_t;

typedef struct {
	uint16	unknown[3];
} aot_params_standard_t;

typedef struct {
	uint8	id;
	uint8	unknown0;
	uint16	unknown1[2];
} aot_params_message_t;

typedef struct {
	uint8	cond;
	uint8	unknown0;
	uint8	ex_opcode;
	uint8	event;
	uint16	unknown1;
} aot_params_event_t;

typedef struct {
	uint16	unknown[3];
} aot_params_flag_change_t;

typedef struct {
	uint16	unknown[3];
} aot_params_water_t;

typedef struct {
	uint16	unknown[3];
} aot_params_move_t;

typedef struct {
	uint16	unknown[3];
} aot_params_typewriter_t;

typedef struct {
	uint16	unknown[3];
} aot_params_itembox_t;

typedef struct {
	uint16	unknown[3];
} aot_params_damage_t;

typedef struct {
	uint16	unknown[3];
} aot_params_status_t;

typedef struct {
	uint16	unknown[3];
} aot_params_drawer_t;

typedef struct {
	uint16	unknown[3];
} aot_params_windows_t;

typedef union {
	aot_params_dummy_t	dummy;
	aot_params_door_t	door;
	aot_params_item_t	item;
	aot_params_standard_t	standard;
	aot_params_message_t	message;
	aot_params_event_t	event;
	aot_params_flag_change_t	flag_change;
	aot_params_water_t	water;
	aot_params_move_t	move;
	aot_params_typewriter_t	typewriter;
	aot_params_itembox_t	itembox;
	aot_params_damage_t	damage;
	aot_params_status_t	status;
	aot_params_drawer_t	drawer;
	aot_params_windows_t	windows;
} aot_params_u;

typedef struct {
	uint8	opcode;
} script_inst_nop_t;

typedef struct {
	uint8	opcode;
	uint8	ret_value;
} script_inst_evt_end_t;

typedef struct {
	uint8	opcode;
} script_inst_evt_next_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	unknown1;
	uint8	event;
} script_inst_evt_chain_t;

typedef struct {
	uint8	opcode;
	uint8	cond;
	uint8	ex_opcode;
	uint8	event;
} script_inst_evt_exec_t;

typedef struct {
	uint8	opcode;
	uint8	event;
} script_inst_evt_kill_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_ifel_ck_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_else_ck_t;

typedef struct {
	uint8	opcode;
} script_inst_endif_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	count;
} script_inst_sleep_t;

typedef struct {
	uint8	opcode;
	uint8	count_lo;
	uint8	count_hi;
} script_inst_sleeping_t;

typedef struct {
	uint8	opcode;
} script_inst_wsleep_t;

typedef struct {
	uint8	opcode;
} script_inst_wsleeping_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
	uint16	count;
} script_inst_for_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_next_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_while_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_ewhile_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
} script_inst_do_t;

typedef struct {
	uint8	opcode;
	uint8	block_length;
} script_inst_edwhile_t;

typedef struct {
	uint8	opcode;
	uint8	varw;
	uint16	block_length;
} script_inst_switch_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	block_length;
	uint16	value;
} script_inst_case_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_default_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_eswitch_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	unknown1;
	uint8	unknown2;
	int16	rel_offset;
} script_inst_goto_t;

typedef struct {
	uint8	opcode;
	uint8	event;
} script_inst_gosub_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_return_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
} script_inst_break_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_for2_t;

typedef struct {
	uint8	opcode;
} script_inst_break_point_t;

typedef struct {
	uint8	opcode;
	uint8	varw;
	uint8	offset;
	uint8	size;
} script_inst_work_copy_t;

typedef struct {
	uint8	opcode;
} script_inst_nop1e_t;

typedef struct {
	uint8	opcode;
} script_inst_nop1f_t;

typedef struct {
	uint8	opcode;
} script_inst_nop20_t;

typedef struct {
	uint8	opcode;
	uint8	array;
	uint8	bit;
	uint8	value;
} script_inst_ck_t;

typedef struct {
	uint8	opcode;
	uint8	array;
	uint8	bit;
	uint8	operation;
} script_inst_set_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	varw;
	uint8	compare;
	uint16	value;
} script_inst_cmp_t;

typedef struct {
	uint8	opcode;
	uint8	varw;
	int16	value;
} script_inst_save_t;

typedef struct {
	uint8	opcode;
	uint8	varw_dst;
	uint8	varw_src;
} script_inst_copy_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	operation;
	uint8	varw;
	uint16	value;
} script_inst_calc_t;

typedef struct {
	uint8	opcode;
	uint8	operation;
	uint8	varw;
	uint8	src;
} script_inst_calc2_t;

typedef struct {
	uint8	opcode;
} script_inst_sce_rnd_t;

typedef struct {
	uint8	opcode;
	uint8	camera;
} script_inst_cut_chg_t;

typedef struct {
	uint8	opcode;
} script_inst_cut_old_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	id;
	uint8	unknown1;
	uint8	unknown2;
	uint8	unknown3;
} script_inst_message_on_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	uint16	unknown0;
	int16	x;
	int16	z;
	int16	w;
	int16	h;
	aot_params_u	aot_params;
} script_inst_aot_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	tex_ctr;
	uint8	wait;
	uint8	pattern;
	uint8	nFloor;
	uint8	Super;
	uint8	type;
	uint16	set_flg;
	uint16	be_flg;
	uint16	attribute;
	int16	x;
	int16	y;
	int16	z;
	int16	cdir_x;
	int16	cdir_y;
	int16	cdir_z;
	int16	offset_x;
	int16	offset_y;
	int16	offset_z;
	int16	size_x;
	int16	size_y;
	int16	size_z;
} script_inst_obj_model_set_t;

typedef struct {
	uint8	opcode;
	uint8	component;
	uint8	index;
} script_inst_work_set_t;

typedef struct {
	uint8	opcode;
	uint8	component;
	int16	value;
} script_inst_speed_set_t;

typedef struct {
	uint8	opcode;
} script_inst_add_speed_t;

typedef struct {
	uint8	opcode;
} script_inst_add_aspeed_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	int16	x;
	int16	y;
	int16	z;
} script_inst_pos_set_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	int16	cdir_x;
	int16	cdir_y;
	int16	cdir_z;
} script_inst_dir_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	int16	value;
} script_inst_member_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	varw;
} script_inst_member_set2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
	int16	x;
	int16	y;
	int16	z;
} script_inst_se_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_sca_id_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	unknown0;
} script_inst_flr_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
	uint16	unknown3;
} script_inst_dir_ck_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	unknown0[4];
	int16	dir;
	int16	x;
	int16	y;
	int16	z;
	uint16	unknown3;
} script_inst_sce_espr_on_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	uint16	unknown0;
	int16	x;
	int16	z;
	int16	w;
	int16	h;
	int16	next_x;
	int16	next_y;
	int16	next_z;
	int16	next_dir;
	uint8	next_stage;
	uint8	next_room;
	uint8	next_camera;
	uint8	unknown1;
	uint8	door_type;
	uint8	door_lock;
	uint8	unknown2;
	uint8	door_locked;
	uint8	door_key;
	uint8	unknown3;
} script_inst_door_aot_set_t;

typedef struct {
	uint8	opcode;
	uint8	screen;
} script_inst_cut_auto_t;

typedef struct {
	uint8	opcode;
	uint8	varw;
	uint8	id;
} script_inst_member_copy_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	unknown1;
	uint8	compare;
	int16	value;
} script_inst_member_cmp_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_plc_motion_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	unknown0;
	uint8	unknown1;
	int16	x;
	int16	z;
} script_inst_plc_dest_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[4];
} script_inst_plc_neck_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_ret_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_plc_flg_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	aot;
	uint8	id;
	uint8	type;
	uint8	status;
	uint8	nFloor;
	uint8	Sound_flg;
	uint8	Model_type;
	uint8	Em_set_flg;
	int16	x;
	int16	y;
	int16	z;
	int16	cdir_y;
	uint16	Motion;
	uint16	Ctr_flg;
} script_inst_sce_em_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint8	unknown2;
} script_inst_col_chg_set_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	aot_params_u	aot_params;
} script_inst_aot_reset_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
} script_inst_aot_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
} script_inst_super_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
} script_inst_super_reset_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_plc_gun_t;

typedef struct {
	uint8	opcode;
	uint8	camera0;
	uint8	camera1;
} script_inst_cut_replace_t;

typedef struct {
	uint8	opcode;
	uint8	anim0;
	uint8	anim1;
	uint8	anim2;
	uint8	anim3;
} script_inst_sce_espr_kill_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
	uint32	unknown5;
	uint16	unknown6;
} script_inst_4d_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	uint16	unknown0;
	int16	x;
	int16	z;
	uint16	w;
	uint16	h;
	uint16	item;
	uint16	amount;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_item_aot_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_sce_key_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_sce_trg_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	unknown1;
	uint8	unknown2;
	uint8	unknown3;
	uint8	unknown4;
} script_inst_sce_bgm_control_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_sce_espr_control_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_sce_fade_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1[3];
	int16	x;
	int16	y;
	int16	z;
	uint16	unknown2[4];
} script_inst_sce_espr3d_on_t;

typedef struct {
	uint8	opcode;
	uint8	operation;
	uint16	unknown0;
	uint16	value;
} script_inst_member_calc_t;

typedef struct {
	uint8	opcode;
	uint8	operation;
	uint8	value;
	uint8	id;
} script_inst_member_calc2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
} script_inst_sce_bgmtbl_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_plc_rot_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	int16	value;
} script_inst_xa_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_weapon_chg_t;

typedef struct {
	uint8	opcode;
	uint8	unknown;
} script_inst_plc_cnt_t;

typedef struct {
	uint8	opcode;
	int8	x;
	int8	y;
} script_inst_sce_shake_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_mizu_div_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
} script_inst_keep_item_ck_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_xa_vol_t;

typedef struct {
	uint8	opcode;
	uint8	component;
	uint8	index;
	uint8	unknown0[3];
	uint16	unknown1[4];
} script_inst_kage_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_cut_be_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
} script_inst_sce_item_lost_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_gun_eff_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
} script_inst_sce_espr_on2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_sce_espr_kill2_t;

typedef struct {
	uint8	opcode;
} script_inst_plc_stop_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	uint16	unknown0;
	int16	x0;
	int16	z0;
	int16	x1;
	int16	z1;
	int16	x2;
	int16	z2;
	int16	x3;
	int16	z3;
	aot_params_u	aot_params;
} script_inst_aot_set_4p_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	uint16	unknown0;
	int16	x0;
	int16	z0;
	int16	x1;
	int16	z1;
	int16	x2;
	int16	z2;
	int16	x3;
	int16	z3;
	int16	next_x;
	int16	next_y;
	int16	next_z;
	int16	next_dir;
	uint8	next_stage;
	uint8	next_room;
	uint8	next_camera;
	uint8	unknown1;
	uint8	door_type;
	uint8	door_lock;
	uint8	unknown2;
	uint8	door_locked;
	uint8	door_key;
	uint8	unknown3;
} script_inst_door_aot_set_4p_t;

typedef struct {
	uint8	opcode;
	uint8	aot;
	uint8	type;
	uint8	trigger;
	uint16	unknown0;
	int16	x0;
	int16	z0;
	int16	x1;
	int16	z1;
	int16	x2;
	int16	z2;
	int16	x3;
	int16	z3;
	uint16	item;
	uint16	amount;
	uint16	unknown1[2];
} script_inst_item_aot_set_4p_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	id;
	uint8	param;
	int16	value;
} script_inst_light_pos_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint16	range;
} script_inst_light_kido_set_t;

typedef struct {
	uint8	opcode;
} script_inst_rbj_reset_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint16	y;
} script_inst_sce_scr_move_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_parts_set_t;

typedef struct {
	uint8	opcode;
	uint8	id;
} script_inst_movie_on_t;

typedef struct {
	uint8	opcode;
} script_inst_splc_ret_t;

typedef struct {
	uint8	opcode;
} script_inst_splc_sce_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
} script_inst_super_on_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
} script_inst_mirror_set_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_sce_fade_adjust_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
	uint32	unknown5;
	uint16	unknown6;
} script_inst_sce_espr3d_on2_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	amount;
} script_inst_sce_item_get_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
} script_inst_sce_line_start_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	int16	unknown1;
	uint16	unknown2;
} script_inst_sce_line_main_t;

typedef struct {
	uint8	opcode;
} script_inst_sce_line_end_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
} script_inst_sce_parts_bomb_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
} script_inst_sce_parts_down_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	r;
	uint8	g;
	uint8	b;
	uint8	dummy;
} script_inst_light_color_set_t;

typedef struct {
	uint8	opcode;
	uint8	camera;
	uint8	id;
	uint8	param;
	int16	value;
} script_inst_light_pos_set2_t;

typedef struct {
	uint8	opcode;
	uint8	dummy;
	uint8	camera;
	uint8	id;
	uint16	range;
} script_inst_light_kido_set2_t;

typedef struct {
	uint8	opcode;
	uint8	camera;
	uint8	id;
	uint8	r;
	uint8	g;
	uint8	b;
} script_inst_light_color_set2_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_se_vol_t;

typedef struct {
	uint8	opcode;
	uint8	compare;
	uint8	value;
} script_inst_81_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint8	unknown1;
} script_inst_82_t;

typedef struct {
	uint8	opcode;
} script_inst_83_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
} script_inst_84_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint16	unknown2;
} script_inst_85_t;

typedef struct {
	uint8	opcode;
} script_inst_poison_ck_t;

typedef struct {
	uint8	opcode;
} script_inst_poison_clr_t;

typedef struct {
	uint8	opcode;
	uint8	id;
	uint8	unknown0;
} script_inst_sce_item_ck_lost_t;

typedef struct {
	uint8	opcode;
} script_inst_89_t;

typedef struct {
	uint8	opcode;
	uint8	dummy[5];
} script_inst_nop8a_t;

typedef struct {
	uint8	opcode;
	uint8	dummy[5];
} script_inst_nop8b_t;

typedef struct {
	uint8	opcode;
	uint8	dummy[7];
} script_inst_nop8c_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
	uint32	unknown5;
	uint32	unknown6;
} script_inst_8d_t;

typedef struct {
	uint8	opcode;
	uint8	unknown0;
	uint16	unknown1;
	uint32	unknown2;
	uint32	unknown3;
	uint32	unknown4;
	uint32	unknown5;
	uint32	unknown6;
} script_inst_8e_t;

typedef union script_inst_u script_inst_t;

union script_inst_u {
	uint8	opcode;
	script_inst_nop_t	i_nop;
	script_inst_evt_end_t	i_evt_end;
	script_inst_evt_next_t	i_evt_next;
	script_inst_evt_chain_t	i_evt_chain;
	script_inst_evt_exec_t	i_evt_exec;
	script_inst_evt_kill_t	i_evt_kill;
	script_inst_ifel_ck_t	i_ifel_ck;
	script_inst_else_ck_t	i_else_ck;
	script_inst_endif_t	i_endif;
	script_inst_sleep_t	i_sleep;
	script_inst_sleeping_t	i_sleeping;
	script_inst_wsleep_t	i_wsleep;
	script_inst_wsleeping_t	i_wsleeping;
	script_inst_for_t	i_for;
	script_inst_next_t	i_next;
	script_inst_while_t	i_while;
	script_inst_ewhile_t	i_ewhile;
	script_inst_do_t	i_do;
	script_inst_edwhile_t	i_edwhile;
	script_inst_switch_t	i_switch;
	script_inst_case_t	i_case;
	script_inst_default_t	i_default;
	script_inst_eswitch_t	i_eswitch;
	script_inst_goto_t	i_goto;
	script_inst_gosub_t	i_gosub;
	script_inst_return_t	i_return;
	script_inst_break_t	i_break;
	script_inst_for2_t	i_for2;
	script_inst_break_point_t	i_break_point;
	script_inst_work_copy_t	i_work_copy;
	script_inst_nop1e_t	i_nop1e;
	script_inst_nop1f_t	i_nop1f;
	script_inst_nop20_t	i_nop20;
	script_inst_ck_t	i_ck;
	script_inst_set_t	i_set;
	script_inst_cmp_t	i_cmp;
	script_inst_save_t	i_save;
	script_inst_copy_t	i_copy;
	script_inst_calc_t	i_calc;
	script_inst_calc2_t	i_calc2;
	script_inst_sce_rnd_t	i_sce_rnd;
	script_inst_cut_chg_t	i_cut_chg;
	script_inst_cut_old_t	i_cut_old;
	script_inst_message_on_t	i_message_on;
	script_inst_aot_set_t	i_aot_set;
	script_inst_obj_model_set_t	i_obj_model_set;
	script_inst_work_set_t	i_work_set;
	script_inst_speed_set_t	i_speed_set;
	script_inst_add_speed_t	i_add_speed;
	script_inst_add_aspeed_t	i_add_aspeed;
	script_inst_pos_set_t	i_pos_set;
	script_inst_dir_set_t	i_dir_set;
	script_inst_member_set_t	i_member_set;
	script_inst_member_set2_t	i_member_set2;
	script_inst_se_on_t	i_se_on;
	script_inst_sca_id_set_t	i_sca_id_set;
	script_inst_flr_set_t	i_flr_set;
	script_inst_dir_ck_t	i_dir_ck;
	script_inst_sce_espr_on_t	i_sce_espr_on;
	script_inst_door_aot_set_t	i_door_aot_set;
	script_inst_cut_auto_t	i_cut_auto;
	script_inst_member_copy_t	i_member_copy;
	script_inst_member_cmp_t	i_member_cmp;
	script_inst_plc_motion_t	i_plc_motion;
	script_inst_plc_dest_t	i_plc_dest;
	script_inst_plc_neck_t	i_plc_neck;
	script_inst_plc_ret_t	i_plc_ret;
	script_inst_plc_flg_t	i_plc_flg;
	script_inst_sce_em_set_t	i_sce_em_set;
	script_inst_col_chg_set_t	i_col_chg_set;
	script_inst_aot_reset_t	i_aot_reset;
	script_inst_aot_on_t	i_aot_on;
	script_inst_super_set_t	i_super_set;
	script_inst_super_reset_t	i_super_reset;
	script_inst_plc_gun_t	i_plc_gun;
	script_inst_cut_replace_t	i_cut_replace;
	script_inst_sce_espr_kill_t	i_sce_espr_kill;
	script_inst_4d_t	i_4d;
	script_inst_item_aot_set_t	i_item_aot_set;
	script_inst_sce_key_ck_t	i_sce_key_ck;
	script_inst_sce_trg_ck_t	i_sce_trg_ck;
	script_inst_sce_bgm_control_t	i_sce_bgm_control;
	script_inst_sce_espr_control_t	i_sce_espr_control;
	script_inst_sce_fade_set_t	i_sce_fade_set;
	script_inst_sce_espr3d_on_t	i_sce_espr3d_on;
	script_inst_member_calc_t	i_member_calc;
	script_inst_member_calc2_t	i_member_calc2;
	script_inst_sce_bgmtbl_set_t	i_sce_bgmtbl_set;
	script_inst_plc_rot_t	i_plc_rot;
	script_inst_xa_on_t	i_xa_on;
	script_inst_weapon_chg_t	i_weapon_chg;
	script_inst_plc_cnt_t	i_plc_cnt;
	script_inst_sce_shake_on_t	i_sce_shake_on;
	script_inst_mizu_div_set_t	i_mizu_div_set;
	script_inst_keep_item_ck_t	i_keep_item_ck;
	script_inst_xa_vol_t	i_xa_vol;
	script_inst_kage_set_t	i_kage_set;
	script_inst_cut_be_set_t	i_cut_be_set;
	script_inst_sce_item_lost_t	i_sce_item_lost;
	script_inst_plc_gun_eff_t	i_plc_gun_eff;
	script_inst_sce_espr_on2_t	i_sce_espr_on2;
	script_inst_sce_espr_kill2_t	i_sce_espr_kill2;
	script_inst_plc_stop_t	i_plc_stop;
	script_inst_aot_set_4p_t	i_aot_set_4p;
	script_inst_door_aot_set_4p_t	i_door_aot_set_4p;
	script_inst_item_aot_set_4p_t	i_item_aot_set_4p;
	script_inst_light_pos_set_t	i_light_pos_set;
	script_inst_light_kido_set_t	i_light_kido_set;
	script_inst_rbj_reset_t	i_rbj_reset;
	script_inst_sce_scr_move_t	i_sce_scr_move;
	script_inst_parts_set_t	i_parts_set;
	script_inst_movie_on_t	i_movie_on;
	script_inst_splc_ret_t	i_splc_ret;
	script_inst_splc_sce_t	i_splc_sce;
	script_inst_super_on_t	i_super_on;
	script_inst_mirror_set_t	i_mirror_set;
	script_inst_sce_fade_adjust_t	i_sce_fade_adjust;
	script_inst_sce_espr3d_on2_t	i_sce_espr3d_on2;
	script_inst_sce_item_get_t	i_sce_item_get;
	script_inst_sce_line_start_t	i_sce_line_start;
	script_inst_sce_line_main_t	i_sce_line_main;
	script_inst_sce_line_end_t	i_sce_line_end;
	script_inst_sce_parts_bomb_t	i_sce_parts_bomb;
	script_inst_sce_parts_down_t	i_sce_parts_down;
	script_inst_light_color_set_t	i_light_color_set;
	script_inst_light_pos_set2_t	i_light_pos_set2;
	script_inst_light_kido_set2_t	i_light_kido_set2;
	script_inst_light_color_set2_t	i_light_color_set2;
	script_inst_se_vol_t	i_se_vol;
	script_inst_81_t	i_81;
	script_inst_82_t	i_82;
	script_inst_83_t	i_83;
	script_inst_84_t	i_84;
	script_inst_85_t	i_85;
	script_inst_poison_ck_t	i_poison_ck;
	script_inst_poison_clr_t	i_poison_clr;
	script_inst_sce_item_ck_lost_t	i_sce_item_ck_lost;
	script_inst_89_t	i_89;
	script_inst_nop8a_t	i_nop8a;
	script_inst_nop8b_t	i_nop8b;
	script_inst_nop8c_t	i_nop8c;
	script_inst_8d_t	i_8d;
	script_inst_8e_t	i_8e;
};
